#!/bin/sh

case "$1" in
    start)
        ip addr add 192.168.1.1/24 dev eth0
        ip link set eth0 up
        ;;
    stop)
        ip addr flush dev eth0
        ip link set eth0 down
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
esac

exit 0
