#!/bin/sh

case "$1" in
    start)
        mkdir -p /mnt/usb


  for i in 1 2 3 4 5 6 7 8 9 10; do
                [ /dev/sda1 ] && break
                sleep 1
        done

        mount /dev/sda1 /mnt/usb
        ;;

    stop)
        umount /mnt/usb
        ;;

    *)
        exit 1
        ;;
esac

exit 0
