#!/bin/sh

case "$1" in
    start)  
	killall nmbd smbd        
	rm -f /etc/samba/smb.conf
    	cp /www/smbusb.conf /etc/samba/smb.conf 
	echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor  
	nmbd -D
        smbd -D



	echo 34 > /sys/class/gpio/export 2>/dev/null
	echo out > "/sys/class/gpio/gpio34/direction"
        for i in 1 0 1 0; do
	echo $i > "/sys/class/gpio/gpio34/value"
	sleep 0.3
	done
        ;;
    stop)
        echo "Stopping..."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
