#!/bin/sh

case "$1" in
    start)
	sysctl -w net.core.rmem_max=26214400 >/dev/null 2>&1
    	sysctl -w net.core.wmem_max=26214400 >/dev/null 2>&1 
	echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
        nice -n -20 udpfsd -fsroot /mnt/usb BIND=192.168.1.1 &

	echo 34 > /sys/class/gpio/export 2>/dev/null
	echo out > "/sys/class/gpio/gpio34/direction"
        for i in 1 0 1 0 1 0 1 0 1 0 1 0; do
	echo $i > "/sys/class/gpio/gpio34/value"
	sleep 0.3
	done

        ;;
    stop)
        echo "Stopping..."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
